resources:
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: vm-import-controller
      namespace: harvester-system
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "0.1.2"
      chart: harvester-vm-import-controller
      enabled: false
      valuesContent: |
        image:
          tag: v0.1.2
        fullnameOverride: harvester-vm-import-controller
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: pcidevices-controller
      namespace: harvester-system
      labels:
        addon.harvesterhci.io/experimental: "true"
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "0.2.3"
      chart: harvester-pcidevices-controller
      enabled: false
      valuesContent: |
        image:
          tag: v0.2.3
        fullnameOverride: harvester-pcidevices-controller

