resources:
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: vm-import-controller
      namespace: harvester-system
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "0.1.8"
      chart: harvester-vm-import-controller
      {{- if and .Addons .Addons.harvester_vm_import_controller }}
      enabled: {{ .Addons.harvester_vm_import_controller.Enabled }}
      {{- else }}
      enabled: false
      {{- end }}
      valuesContent: |
        image:
          tag: v0.1.8
        fullnameOverride: harvester-vm-import-controller
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: pcidevices-controller
      namespace: harvester-system
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "0.3.2"
      chart: harvester-pcidevices-controller
      {{- if and .Addons .Addons.harvester_pcidevices_controller }}
      enabled: {{ .Addons.harvester_pcidevices_controller.Enabled }}
      {{- else }}
      enabled: false
      {{- end }}
      valuesContent: |
        image:
          tag: v0.3.2
        fullnameOverride: harvester-pcidevices-controller
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: rancher-logging
      namespace: cattle-logging-system
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "103.0.0+up3.17.10"
      chart: rancher-logging
      {{- if and .Addons .Addons.rancher_logging }}
      enabled: {{ .Addons.rancher_logging.Enabled }}
      {{- else }}
      enabled: false
      {{- end }}
      valuesContent: |
        systemdLogPath: /var/log/journal
        disablePvc: true
        additionalLoggingSources:
          rke2:
            enabled: true
          kubeAudit:
            enabled: true
            auditFilename: "audit.log"
            pathPrefix: "/var/lib/rancher/rke2/server/logs/"
            loggingRef: "harvester-kube-audit-log-ref"
            fluentbit:
              logTag: kube-audit
              tolerations:
              - key: node-role.kubernetes.io/controlplane
                value: "true"
                effect: NoSchedule
              - key: node-role.kubernetes.io/etcd
                value: "true"
                effect: NoExecute
        fluentd:
          resources:
            limits:
              cpu: 1000m
              memory: 800Mi
            requests:
              cpu: 100m
              memory: 200Mi
        fluentbit:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
        eventTailer:
          name: harvester-default
          namespace: cattle-logging-system
          controlNamespace: cattle-logging-system
          workloadOverrides:
            containers:
            - image: rancher/harvester-eventrouter:v0.1.2
              name: event-tailer
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 20m
                  memory: 20Mi
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: rancher-monitoring
      namespace: cattle-monitoring-system
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "103.0.3+up45.31.1"
      chart: rancher-monitoring
      {{- if and .Addons .Addons.rancher_monitoring }}
      enabled: {{ .Addons.rancher_monitoring.Enabled }}
      {{- else }}
      enabled: false
      {{- end }}
      valuesContent: |
        alertmanager:
          enabled: true
          config:
            global:
              resolve_timeout: 5m
          service:
            port: 9093
          alertmanagerSpec:
            {{- if .Vip }}
            externalUrl: "https://{{ .Vip }}/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093/proxy/"
            {{- end }}
            retention: 120h
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: harvester-longhorn
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 5Gi
            resources:
              limits:
                memory: 600Mi
                cpu: 1000m
              requests:
                memory: 100Mi
                cpu: 100m
        grafana:
          persistence:
            enabled: true
            size: 2Gi
            storageClassName: harvester-longhorn
            type: pvc
            accessModes:
            - ReadWriteOnce
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
        prometheus:
          service:
            port: 9090
          prometheusSpec:
            evaluationInterval: 1m
            resources:
              limits:
                cpu: 1000m
                memory: 2500Mi
              requests:
                cpu: 750m
                memory: 1750Mi
            retention: 5d
            retentionSize: 50GiB
            scrapeInterval: 1m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi
                  storageClassName: harvester-longhorn
                  volumeMode: Filesystem
            {{- if .Vip }}
            externalUrl: "https://{{ .Vip }}/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/"
            {{- end }}
        prometheus-node-exporter:
          resources:
            limits:
              cpu: 200m
              memory: 180Mi
            requests:
              cpu: 100m
              memory: 30Mi
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: harvester-seeder
      namespace: harvester-system
    labels:
      addon.harvesterhci.io/experimental: "true"
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "0.1.1"
      chart: harvester-seeder
      {{- if and .Addons .Addons.harvester_seeder}}
      enabled: {{ .Addons.harvester_seeder.Enabled }}
      {{- else }}
      enabled: false
      {{- end }}
      valuesContent: |
        image:
          tag: v0.1.2
        fullnameOverride: harvester-seeder
  - apiVersion: harvesterhci.io/v1beta1
    kind: Addon
    metadata:
      name: nvidia-driver-toolkit
      namespace: harvester-system
    spec:
      repo: http://harvester-cluster-repo.cattle-system.svc/charts
      version: "0.1.1"
      chart: nvidia-driver-runtime
      {{- if and .Addons .Addons.nvidia_driver_toolkit}}
      enabled: {{ .Addons.nvidia_driver_toolkit.Enabled }}
      {{- else }}
      enabled: false
      {{- end }}
      valuesContent: |
        image:
          tag: sle-micro-head
          repo: rancher/harvester-nvidia-driver-toolkit
        driverLocation:  "HTTPENDPOINT/NVIDIA-Linux-x86_64-vgpu-kvm.run" 
        fullnameOverride: nvidia-driver-runtime
